site_name: Artur Domingues
docs_dir: docs
repo_url: https://github.com/ArturDomingues/arturdomingues.github.io
theme:
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucid/sun-moon
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: lucid/sun
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: lucid/moon
        name: Switch to system preference
  name: material
  language: en
use_directory_urls: false
nav:
  - Home: index.md
